# Generated by Django 2.0.6 on 2018-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('deviceType', models.CharField(choices=[('SENSOR', 'Dispositivo de Sensores'), ('ACTUATOR', 'Dispositivo de Actuadores Simples')], default='SENSOR', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
