# Generated by Django 2.0.6 on 2018-06-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceType',
            field=models.CharField(choices=[('SENSOR', 'Dispositivo de Sensores'), ('ACTUATOR', 'Dispositivo de Actuadores Simples')], default='SENSOR', max_length=10),
        ),
    ]
