
TYPE_SENSOR = 'SENSOR'
TYPE_ACTUATOR = 'ACTUATOR'
TYPE_CONTROLLER = 'CONTROL'

COMPONENT_TYPES = (
    (TYPE_SENSOR, 'Sensor'),
    (TYPE_ACTUATOR, 'Actuador'),
    (TYPE_CONTROLLER, 'Controlador'),
)

SENSOR_TYPE_DOOR = 'DOOR'
SENSOR_TYPE_IR = 'IR'
SENSOR_TYPES = (
    (SENSOR_TYPE_DOOR, 'Sensor de Puerta'),
    (SENSOR_TYPE_IR, 'Sensor Infrarojo'),
)

NUMBER_TO_SENSOR_TYPE = {
    0: 'NONE',
    1: SENSOR_TYPE_DOOR,
    2: SENSOR_TYPE_IR
}

ACTUATOR_TYPE_HORN = 'Bocina'
ACTUATOR_TYPES = (
    (ACTUATOR_TYPE_HORN, 'Bocina'),
)

CONTROLLER_TYPE_SIMPLE = 'SIMPLE'
CONTROLLER_TYPES = (
    (CONTROLLER_TYPE_SIMPLE, 'Controlador Simple'),
)
