# Generated by Django 3.0.8 on 2020-08-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_module_attr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(choices=[('OTHER', 'Otro Dispositivo'), ('SENSOR', 'Dispositivo de Sensores'), ('ACTUATOR', 'Dispositivo de Actuadores')], default='OTHER', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('INI', 'Configurando'), ('OK', 'Correcto'), ('ERROR', 'Error'), ('DISCO', 'Desconectado')], default='INI', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attrs', models.ManyToManyField(related_name='_device_attrs_+', to='django_module_attr.Attribute')),
                ('container', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.Device')),
                ('metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='django_module_attr.GenericData')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
