# Generated by Django 3.0.8 on 2020-08-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20200805_1943'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='version',
        ),
        migrations.AddField(
            model_name='device',
            name='external_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='locations.Location'),
            preserve_default=False,
        ),
    ]
