# Generated by Django 3.0.8 on 2020-09-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacters', '0001_initial'),
        ('django_module_attr', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='manufacter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='manufacters.Manufacter'),
        ),
        migrations.AddField(
            model_name='device',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='django_module_attr.GenericData'),
        ),
    ]
