# Generated by Django 3.0.8 on 2020-08-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20200805_1943'),
        ('devices', '0002_auto_20200805_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='locations.Location'),
        ),
    ]
