# Generated by Django 2.0.6 on 2018-07-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_auto_20180630_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('sensorType', models.CharField(choices=[('HUM_TEMP', 'Humedad - Temperatura'), ('GP_2', 'Sensor de Gas')], max_length=10)),
                ('lastRead', models.TextField(max_length=500, null=True)),
                ('lastUpdate', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.Sensor')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
