# Generated by Django 3.0.8 on 2020-08-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200805_1943'),
        ('components', '0002_auto_20200802_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='external_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='devices.Device'),
        ),
    ]
