# Generated by Django 3.0.8 on 2020-08-02 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('OTHER', 'Otro')], default='OTHER', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childs', to='locations.Location')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrador'), ('READ', 'Lectura')], default='READ', max_length=10)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='locations.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
