# Generated by Django 3.0.8 on 2020-08-02 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Otro'), ('HOME', 'Casa'), ('ROOM', 'Habitacion')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='access',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Administrador'), ('USER', 'Usuario'), ('READ', 'Lectura')], default='READ', max_length=10),
        ),
    ]
