# Generated by Django 3.0.8 on 2020-09-20 20:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_module_attr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manu_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(choices=[('MQTT', 'MQTT'), ('REST', 'API REST')], default='MQTT', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='django_module_attr.GenericData')),
            ],
        ),
    ]
